<?xml version="1.0" encoding="utf-8"?><Database Name="EPower" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=EPower;User ID=sa" SettingsObjectName="ReportDemo.Properties.Settings" SettingsPropertyName="EPowerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_LICENSE_GENERATE" Member="TBL_LICENSE_GENERATEs">
    <Type Name="TBL_LICENSE_GENERATE">
      <Column Name="LICENSE_GENERATE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SCHEDULE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_ON" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LAST_MODIFIED" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IS_ACTIVE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TLKP_CUSTOMER_CONNECTION_TYPE" Member="TLKP_CUSTOMER_CONNECTION_TYPEs">
    <Type Name="TLKP_CUSTOMER_CONNECTION_TYPE">
      <Column Name="CUSTOMER_CONNECTION_TYPE_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CUSTOMER_CONNECTION_TYPE_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CURRENCY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TARIFF" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="NONLICENSE_CUSTOMER_GROUP_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TLKP_CUSTOMER_GROUP" Member="TLKP_CUSTOMER_GROUPs">
    <Type Name="TLKP_CUSTOMER_GROUP">
      <Column Name="CUSTOMER_GROUP_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CUSTOMER_GROUP_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TLKP_CURRENCY" Member="TLKP_CURRENCies">
    <Type Name="TLKP_CURRENCY">
      <Column Name="CURRENCY_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CURRENCY_NAME" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IS_DEFAULT_CURRENCY" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DIGITS_AFTER_DECIMAL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CURRENCY_SING" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CURRENCY_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_COMPANY" Member="TBL_COMPANies">
    <Type Name="TBL_COMPANY">
      <Column Name="COMPANY_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COMPANY_NAME" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="VILLAGE_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LICENSE_NAME_KH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="COMPANY_LOGO" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LICENSE_NUMBER" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LICENSE_NAME" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="COMPANY_NAME_EN" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LICENSE_TYPE" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>